# Generated by Django 5.1 on 2024-10-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doankhoa',
            fields=[
                ('maDK', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tenDK', models.CharField(max_length=100)),
            ],
        ),
    ]
