# Generated by Django 5.1 on 2024-10-05 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doankhoa',
            options={'verbose_name': 'Đoàn Khoa', 'verbose_name_plural': 'Các Đoàn Khoa'},
        ),
        migrations.AlterModelTable(
            name='doankhoa',
            table='doankhoa',
        ),
        migrations.CreateModel(
            name='Chidoan',
            fields=[
                ('maCD', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tenCD', models.CharField(max_length=255)),
                ('maDK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doankhoa')),
            ],
            options={
                'verbose_name': 'Chi Đoàn',
                'verbose_name_plural': 'Các Chi Đoàn',
                'db_table': 'chidoan',
            },
        ),
    ]
