# Generated by Django 5.1 on 2024-10-11 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_doankhoa_options_alter_doankhoa_table_chidoan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doankhoa',
            name='tenDK',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Doanvien',
            fields=[
                ('maDV', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tenDV', models.CharField(max_length=255)),
                ('ngay_sinh', models.DateField()),
                ('gioi_tinh', models.PositiveSmallIntegerField(choices=[(0, 'Nam'), (1, 'Nữ')], default=0)),
                ('que_quan', models.CharField(max_length=225)),
                ('sdt', models.CharField(blank=True, max_length=15, null=True)),
                ('ngay_vao_doan', models.DateField()),
                ('maCD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chidoan')),
            ],
        ),
    ]
