# Generated by Django 5.1 on 2024-10-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_doankhoa_tendk_doanvien'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doanvien',
            options={'verbose_name': 'Đoàn Viên', 'verbose_name_plural': 'Đoàn Viên'},
        ),
        migrations.AlterModelTable(
            name='doanvien',
            table='doanvien',
        ),
    ]
