# Generated by Django 5.1 on 2024-10-17 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_doanvien_options_alter_doanvien_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hocky',
            fields=[
                ('maHK', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tenHK', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Học Kỳ',
                'verbose_name_plural': 'Các Học Kỳ',
                'db_table': 'hocky',
            },
        ),
        migrations.CreateModel(
            name='Doanphi',
            fields=[
                ('maDP', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('so_tien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trang_thai', models.CharField(choices=[('da_dong', 'Đã đóng'), ('chua_dong', 'Chưa đóng'), ('tre_han', 'Trễ hạn')], default='chua_dong', max_length=20)),
                ('maDV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doanvien')),
                ('maHK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hocky')),
            ],
            options={
                'verbose_name': 'Đoàn Phí',
                'verbose_name_plural': 'Các Đoàn Phí',
                'db_table': 'doanphi',
            },
        ),
    ]
