# Generated by Django 5.1 on 2024-10-19 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_doanvien_options_alter_doanvien_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chucvu',
            fields=[
                ('maCV', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tenCV', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Chức Vụ',
                'verbose_name_plural': 'Các Chức VỤ',
                'db_table': 'chucvu',
            },
        ),
        migrations.CreateModel(
            name='Hocky',
            fields=[
                ('maHK', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tenHK', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Học Kỳ',
                'verbose_name_plural': 'Các Học Kỳ',
                'db_table': 'hocky',
            },
        ),
        migrations.AlterModelOptions(
            name='doanvien',
            options={'verbose_name': 'Đoàn Viên', 'verbose_name_plural': 'Các Đoàn Viên'},
        ),
        migrations.AlterField(
            model_name='doanvien',
            name='maDV',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doanvien',
            name='que_quan',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doanvien',
            name='sdt',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AlterField(
            model_name='doanvien',
            name='tenDV',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='doanvien',
            name='maCV',
            field=models.ForeignKey(default='Đoàn viên', on_delete=django.db.models.deletion.CASCADE, to='home.chucvu'),
        ),
        migrations.CreateModel(
            name='Doanphi',
            fields=[
                ('maDP', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sotien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trangthai', models.PositiveSmallIntegerField(choices=[(0, 'Chưa đóng'), (1, 'Đã đóng')], default=0)),
                ('maDV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doanvien')),
                ('hocky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hocky')),
            ],
            options={
                'verbose_name': 'Đoàn Phí',
                'verbose_name_plural': 'Các Đoàn Phí',
                'db_table': 'doanphi',
            },
        ),
    ]
