# Generated by Django 5.1 on 2024-10-17 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_hocky_doanphi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doanphi',
            old_name='maDV',
            new_name='doanvien',
        ),
        migrations.RenameField(
            model_name='doanphi',
            old_name='maHK',
            new_name='hocky',
        ),
        migrations.RenameField(
            model_name='doanphi',
            old_name='so_tien',
            new_name='sotien',
        ),
        migrations.RenameField(
            model_name='doanphi',
            old_name='trang_thai',
            new_name='trangthai',
        ),
    ]
